Project setup
dan9Protasenia/Scraper_task pull request #1
Opened 2024-01-22 11:53 UTC by dan9Protasenia

## what is done

1. Implemented poetry
2. Implemented Web Scraper Interface
3. Developed Hacker News Scraper with Selenium
4. Developed New York Times Scraper with Beautiful Soup
5. Defined Pydantic Data Models

2024-01-22 11:57 UTC, dan9Protasenia commented
@RoTorEx

2024-01-25 20:14 UTC, RoTorEx requested changes

2024-01-25 20:14 UTC, RoTorEx commented on src/b4s/hh_scraper.py
> +from ..scraper_interface import WebScraperInterface
Призываю никогда не использовать относительные импорты, только если ты не работаешь в рамках одного пакета, чтобы собрать все объекты с модулей в один верхний модуль, его называют иногда _base.py_, либо, что я и делаю, выношу все объекты с модулей в *__init__.py*, как ты можешь сделать в своём *__init__.py* по пути _src/core/schemas_.

Как минимум такие штуки могут ломаться случайно и вызвать циклические импорты, и они визуально не ясны.


Здесь тебе нужно 
```
from src.core.schamas.data import ...
```

Либо, если ты внутри *src/core/schemas/__init__.py* соберёшь все импорты аля так:
```
from .data import Article

__all__ = [
    "Article"
]
```
То сможешь импортировать сразу из пакета:
```
from src.core.schamas import ...
```
Очень полезно, когда понадобиться импортировать десятки разных схем или моделей.

2024-01-25 20:14 UTC, RoTorEx commented on src/b4s/hh_scraper.py
> +        ...
Если это твой конечный интерфейс, то лучше `raise NotImplementedError`, она более ясна, что тут ещё можно что-то расширить

2024-01-25 20:14 UTC, RoTorEx commented on src/b4s/nyt_scraper.py
> +from ..scraper_interface import WebScraperInterface
Всё тоже самое, не стреляй ни себе, ни коллегам в ногу

2024-01-25 20:14 UTC, RoTorEx commented on src/b4s/nyt_scraper.py
> +                continue
1. Ошибка должна быть залогирована, если ты уже её перехватываешь
2. Почему в других реализациях нет обработки, если тут она падает?

2024-01-25 20:14 UTC, RoTorEx commented on src/main.py
> +from .selenium.rabota_scraper import RabotaScraper
Тоже самое

2024-01-25 20:14 UTC, RoTorEx commented on src/main.py
> +    if len(sys.argv) > 1:
Как обрабатывается запуск без аргументов?

2024-01-25 20:14 UTC, RoTorEx commented on src/main.py
> +            print("NYT data scraping and writing complete.")
Мне нравится идея с аргументами, но
1. Беглым чтением не ясно что откуда идёт и куда вызывается. Ты ведь можешь закрыть все принты внутри классов или даже внутри протокола, верно? Тем самым не раздуешь мэин функцию и не будет такой мешанины
2. Я предлагаю более аккуратное решение:
  - а) сделай маленькие функции, каждая из которых отвечает за вызов своего класса по аргументу где происходит вызов уже методов класса
  - б) используй инкапсуляцию, то есть делай некоторые рабочие методы приватными или закрытыми, а оставь только один или несколько внешних апи для запуска, например `action` или `run`. Мне кажется, что для любого парсера будет сделана запись файл, то есть он уже может быть сокрыт, как и фетч хтмл? (Предпочтительный)

2024-01-25 20:14 UTC, RoTorEx commented on src/scraper_interface.py
> +            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
Тут сразу длина строки бросается в глаза, точно больше 120

2024-01-25 20:14 UTC, RoTorEx commented on src/scraper_interface.py
> +    def apply_filters(self, **kwargs) -> None:
Аннотации для параметров

2024-01-25 20:14 UTC, RoTorEx commented on src/scraper_interface.py
> +        self.driver = webdriver.Chrome()
О чём я начал выше писать в пункте б.
Для б4с нам не нужно готовить гугл. Ты можешь на базе это интерфейса сделать ещё промежуточный б4с и силениум класс, либо уже в конечных классах используй раздельный методы подготовки, которые тоже можно сделать приватными, или использовать как классметоды вообще, в общем и целом это прокачай :)

И почему ты и два раза определяешь вебдрайвер?

2024-01-25 20:14 UTC, RoTorEx commented on src/selenium/hacker_news_scraper.py
> +from ..scraper_interface import WebScraperInterface
+1

2024-01-25 20:14 UTC, RoTorEx commented on src/selenium/hacker_news_scraper.py
> +        return data
Кидается в глаза разный код стайл в конечных классах

2024-01-25 20:14 UTC, RoTorEx commented on src/selenium/rabota_scraper.py
> +from ..scraper_interface import WebScraperInterface
+1

2024-01-25 20:16 UTC, RoTorEx commented on src/scraper_interface.py
Кстати это тоже можно вынести в _core.py_, он там будет архитектурно правильно выглядеть

2024-01-27 16:54 UTC, merged